env:
  - GO111MODULE=on
  - GOPROXY=https://proxy.golang.org,direct
before:
  hooks:
    - go mod download
builds:
  - main: ./cmd/helm-cm-push
    binary: ./bin/helm-cm-push
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64

archives:
  - id: release
    format: tar.gz
    files:
      - LICENSE
      - plugin.yaml
