name: "cm-push"
version: "0.8.1"
usage: "Please see https://github.com/AliyunContainerService/helm-acr for usage"
description: "Push chart package to Alibaba Container Registry"
command: "$HELM_PLUGIN_DIR/bin/helm-cm-push"
downloaders:
  - command: "bin/helm-cm-push"
    protocols:
      - "acr"
useTunnel: false
hooks:
  install: "cd $HELM_PLUGIN_DIR; scripts/install_plugin.sh"
  update: "cd $HELM_PLUGIN_DIR; scripts/install_plugin.sh"